# Configure RuboCop
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - support/**/*
    - vendor/**/*
Encoding:
  Enabled: false
LineLength:
  Max: 400
MethodLength:
  Max: 35
ParenthesesAsGroupedExpression:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/TrailingBlankLines:
  EnforcedStyle: final_newline
DefaultFormatter: emacs
